version: 2.1

jobs:
  checkout_and_unit_test:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Checkout and Unit Tests"

  deploy_backend:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Deploy Backend"

  integration_tests_backend:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Integration Tests Backend"

  deploy_staging:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Deploy Staging"

  acceptance_tests_1:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Acceptance Tests 1"

  acceptance_tests_2:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Acceptance Tests 2"

  acceptance_tests_3:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Acceptance Tests 3"

  acceptance_tests_4:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Acceptance Tests 4"

  deploy_production:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Deploy Production"

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_and_unit_test
      - deploy_backend:
          requires:
            - checkout_and_unit_test
      - integration_tests_backend:
          requires:
            - deploy_backend
      - deploy_staging:
          requires:
            - integration_tests_backend
      - acceptance_tests_1:
          requires:
            - deploy_staging
      - acceptance_tests_2:
          requires:
            - deploy_staging
      - acceptance_tests_3:
          requires:
            - deploy_staging
      - acceptance_tests_4:
          requires:
            - deploy_staging
      - deploy_production:
          requires:
            - acceptance_tests_1
            - acceptance_tests_2
            - acceptance_tests_3
            - acceptance_tests_4
